### ISSUE TITLE
master does not compile: #1443 calls fresh_pool() which #1428 removed

### ISSUE THREAD

**Issue by ormeilu** [rolter-ai/rolter#1487]
## master does not compile

`quality / fmt / clippy` fails on `master`, and has since #1443 merged:

```
error[E0425]: cannot find function `fresh_pool` in this scope
    --> crates/rolter-control/tests/control_integration.rs:9162:16
9162 |     let pool = fresh_pool().await;
     |                ^^^^^^^^^^ not found in this scope
error: could not compile `rolter-control` (test "control_integration")
```

This blocks every open PR: each one inherits the broken file, so `fmt / clippy` is red across the whole queue regardless of its own contents.

## Cause: a semantic merge conflict, not a textual one

Two PRs that never touched the same lines:

- **#1428** (`7896dbd`, *drop the per-test schema when an integration test finishes*) removed the `fresh_pool()` helper, replacing it with the `TestSchema` guard — the pattern AGENTS.md now mandates, so the schema is returned even when a test panics (#1364).
- **#1443** (`19c2e82`, *list every project in an org in one request*) added `org_projects_lists_every_team_in_the_org_and_no_other()`, written against the older base, still calling `fresh_pool()`.

Git merged both cleanly because they touch different regions of the file. Each was green against **its own** base. The combination does not compile, and nothing caught it until the next push to `master`.

This is the failure mode branch-protection status checks cannot see: CI validated each PR against a base that no longer existed by the time it merged.

## Fix

Use the current pattern, as every other test in the file does:

```rust
let db = fresh_db().await;
let pool = db.pool().clone();
```

`db` is bound for the whole test, so the schema guard outlives the pool — required by AGENTS.md and by #1364.

## Verification

- Reproduced on `master` first: `error[E0425]` as above.
- After the fix: `cargo fmt --all --check` clean, `cargo clippy -p rolter-control --features postgres --all-targets -- -D warnings` clean.
- Against a real Postgres 16: the previously-uncompilable test passes, and the full suite is green — **384 unit + 64 integration**, where the 64th is this test now compiling.

## Worth considering separately

Requiring PRs to be up to date with `master` before merge would have caught this, at the cost of more rebasing. Not proposed here — flagging that this class of break is invisible to the current gate.

---
_Generated by [Claude Code](https://claude.ai/code)_
