### ISSUE TITLE
fix(ci): two green PRs merged into a red master — no gate runs against the post-merge tree

### ISSUE THREAD

**Issue by ormeilu** [rolter-ai/rolter#1150]
## What happened

`master` at c8b6d0dc does not compile:

```
error[E0063]: missing field `allow_custom_api_base` in initializer of `rolter_core::ProviderConfig`
  --> crates/rolter-gateway/tests/client_disconnect.rs:87:27
```

Two pull requests were each green on their own branch and merged within hours of each other:

- #1132 added the `allow_custom_api_base` field to `ProviderConfig`
- #1138 added `crates/rolter-gateway/tests/client_disconnect.rs`, which constructs `ProviderConfig` with a full struct literal

Neither branch contained the other's change, so neither run could see the break. It only appeared once both were on `master` — and it appeared as a red `ci-ok` on the *next* unrelated PR (#1146, a UI-only change), which is the expensive part: the failure surfaces on work that did not cause it.

## Two separate causes

**1. No merge-queue / required up-to-date branch.** GitHub will merge a PR whose branch is behind `master` without re-running the gate against the merge result. A merge queue, or "require branches to be up to date before merging", is what makes semantic conflicts like this impossible.

**2. `ProviderConfig` has no `Default`.** It has 16 fields and every test constructs the full literal, so *adding a field is a breaking change to every test in the workspace* — the compiler catches it, but only after both halves are on the same tree. A `Default` impl (or a test-only builder) would turn this class of merge into a no-op.

## Done when

- Adding a field to `ProviderConfig` no longer requires editing every test that constructs one — `Default` (or a `#[cfg(test)]` builder) exists and the existing tests use `..Default::default()`
- and a decision is recorded on whether `rolter-ai/rolter` turns on a merge queue or requires up-to-date branches, with the reasoning in `docs/development/`

## Immediate fix

The compile error itself is fixed in the PR that references this issue; this issue is about the two reasons it could happen.
